### ISSUE TITLE
Some questions about the details of implement

### ISSUE THREAD

**Issue by HengshengZ** [tkipf/relational-gcn#1]
Hi,Thomas
I have two questions:
- In `train.py ` the variable `X_in` in this code ` model= Model(input=[X_in] + A_in, output=Y)`,is generated from `Input(shape=(X.shape[1],), sparse=True)` .And it should be viewed as the features for each nodes.But `X` is generated from `X = sp.csr_matrix(A[0].shape)`,where `A` is got from `A = data['A']`.According to the definitnion of `prepare_dataset.py `,`A` represents the adjacent matrix.Maybe I don't get the definition of `sp.csr_matrix`,I think `X` is full of zero with the shape same as `A` and it doesn't represent features.
- As you said,R-GCN is primarily motivated as an extension of GCNs.So,is the spectral theory or Chebyshev polynomial basis filters applied in R-GCN?
I'm new to this filed of research and not familiar to Keras yet,and thank you for your clarification.

**Comment by tkipf** [comment]
Hi, thanks for your questions.

1) X is a feature matrix (in general with shape NxD where N is the number of nodes and D is the number of features). Since in the absence of features it makes sense to assign a unique one-hot vector for each node, we end up having an NxN matrix in this case (i.e. the same shape as A).
2) No.

**Comment by guotong1988** [comment]
THX
